# Databricks notebook source
REQUESTS_AND_RESPONSES_TABLE_NAME = 'request_response'
REQUESTS_AND_RESPONSES_DATABASE_NAME = 'mps_archive'

MPS_DIAGNOSTICS_TABLE_NAME = 'mps_diagnostics'

MPS_SANITY_CHECK_LOG_TABLE_NAME = 'sanity_check_logger'

REQUESTS_AND_RESPONSES_DELTA_TABLE_NAME = 'request_response_delta'
MPS_DIAGNOSTICS_DELTA_TABLE_NAME = 'mps_diagnostics_delta'

PDS_FULL_TABLE_NAME = 'full'
PDS_FULL_DATABASE_NAME = 'pds'

UNMANAGED_DATASETS = ['adhoc', 'mpsaas']

# COMMAND ----------

def drop_keys(key_dict, blacklist):
  return [value for (key, value) in key_dict.items() if key not in blacklist]

# pds dictionary keys
PDS_KEYS = {
  'FROM_KEY': 'from',
  'TO_KEY': 'to',
  'CODE_KEY': 'code',
  'SED_HIGH_KEY': 'sedHigh',
  'SED_LOW_KEY': 'sedLow',
  'VALUE_KEY': 'value'
}

# pds schema
PDS_SCHEMA = {
  'NHS_NUMBER_COL': {
    'NAME': 'nhs_number',
    'KEYS': []
  },
  'REPLACEMENT_OF_COL': {
    'NAME': 'replacementOf',
    'KEYS': drop_keys(PDS_KEYS, ['CODE_KEY'])
  },
  'CONFIDENTIALITY_CODE_COL': {
    'NAME': 'confidentialityCode',
    'KEYS': drop_keys(PDS_KEYS, ['VALUE_KEY'])
  },
  'CONFIDENTIALITY_CODE_HISTORY_COL': {
    'NAME': 'confidentialityCode_history',
    'KEYS': drop_keys(PDS_KEYS, ['VALUE_KEY'])
  }
}

# COMMAND ----------

# request and response table columns
DATASET_ID_COL = 'dataset_id'
LOCAL_ID_COL = 'local_id'
UNIQUE_REFERENCE_COL = 'unique_reference'
REQ_CREATED_COL = 'req_created'
REQ_NHS_NO_COL = 'req_NHS_NO'
REQ_FAMILY_NAME_COL = 'req_FAMILY_NAME'
REQ_GIVEN_NAME_COL = 'req_GIVEN_NAME'
REQ_OTHER_GIVEN_NAME_COL = 'req_OTHER_GIVEN_NAME'
REQ_GENDER_COL = 'req_GENDER'
REQ_DATE_OF_BIRTH_COL = 'req_DATE_OF_BIRTH'
REQ_POSTCODE_COL = 'req_POSTCODE'
REQ_DATE_OF_DEATH_COL = 'req_DATE_OF_DEATH'
REQ_ADDRESS_LINE1_COL = 'req_ADDRESS_LINE1'
REQ_ADDRESS_LINE2_COL = 'req_ADDRESS_LINE2'
REQ_ADDRESS_LINE3_COL = 'req_ADDRESS_LINE3'
REQ_ADDRESS_LINE4_COL = 'req_ADDRESS_LINE4'
REQ_ADDRESS_LINE5_COL = 'req_ADDRESS_LINE5'
REQ_ADDRESS_DATE_COL = 'req_ADDRESS_DATE'
REQ_GP_PRACTICE_CODE_COL = 'req_GP_PRACTICE_CODE'
REQ_NHAIS_POSTING_ID_COL = 'req_NHAIS_POSTING_ID'
REQ_AS_AT_DATE_COL = 'req_AS_AT_DATE'
REQ_LOCAL_PATIENT_ID_COL = 'req_LOCAL_PATIENT_ID'
REQ_INTERNAL_ID_COL = 'req_INTERNAL_ID'
REQ_TELEPHONE_NUMBER_COL = 'req_TELEPHONE_NUMBER'
REQ_MOBILE_NUMBER_COL = 'req_MOBILE_NUMBER'
REQ_EMAIL_ADDRESS_COL = 'req_EMAIL_ADDRESS'
RES_CREATED_COL = 'res_created'
RES_REQ_NHS_NUMBER_COL = 'res_REQ_NHS_NUMBER'
RES_FAMILY_NAME_COL = 'res_FAMILY_NAME'
RES_GIVEN_NAME_COL = 'res_GIVEN_NAME'
RES_OTHER_GIVEN_NAME_COL = 'res_OTHER_GIVEN_NAME'
RES_GENDER_COL = 'res_GENDER'
RES_DATE_OF_BIRTH_COL = 'res_DATE_OF_BIRTH'
RES_DATE_OF_DEATH_COL = 'res_DATE_OF_DEATH'
RES_ADDRESS_LINE1_COL = 'res_ADDRESS_LINE1'
RES_ADDRESS_LINE2_COL = 'res_ADDRESS_LINE2'
RES_ADDRESS_LINE3_COL = 'res_ADDRESS_LINE3'
RES_ADDRESS_LINE4_COL = 'res_ADDRESS_LINE4'
RES_ADDRESS_LINE5_COL = 'res_ADDRESS_LINE5'                    
RES_POSTCODE_COL = 'res_POSTCODE'  
RES_GP_PRACTICE_CODE_COL = 'res_GP_PRACTICE_CODE'
RES_NHAIS_POSTING_ID_COL = 'res_NHAIS_POSTING_ID'
RES_AS_AT_DATE_COL = 'res_AS_AT_DATE'
RES_LOCAL_PATIENT_ID_COL = 'res_LOCAL_PATIENT_ID'
RES_INTERNAL_ID_COL = 'res_INTERNAL_ID'
RES_TELEPHONE_NUMBER_COL = 'res_TELEPHONE_NUMBER'
RES_MOBILE_NUMBER_COL = 'res_MOBILE_NUMBER'
RES_EMAIL_ADDRESS_COL = 'res_EMAIL_ADDRESS'
RES_SENSITIVITY_FLAG_COL = 'res_SENSITIVTY_FLAG'
RES_MPS_ID_COL = 'res_MPS_ID'
RES_ERROR_SUCCESS_CODE_COL = 'res_ERROR_SUCCESS_CODE'
RES_MATCHED_NHS_NO_COL = 'res_MATCHED_NHS_NO'
RES_MATCHED_ALGORITHM_INDICATOR_COL = 'res_MATCHED_ALGORITHM_INDICATOR'
RES_MATCHED_CONFIDENCE_PERCENTAGE_COL = 'res_MATCHED_CONFIDENCE_PERCENTAGE'
RES_ALGORITHMIC_TRACE_FAMILY_NAME_SCORE_PERC_COL = 'res_ALGORITHMIC_TRACE_FAMILY_NAME_SCORE_PERC'
RES_ALGORITHMIC_TRACE_GIVEN_NAME_SCORE_PERC_COL = 'res_ALGORITHMIC_TRACE_GIVEN_NAME_SCORE_PERC'
RES_ALGORITHMIC_TRACE_DOB_SCORE_PERC_COL = 'res_ALGORITHMIC_TRACE_DOB_SCORE_PERC'
RES_ALGORITHMIC_TRACE_GENDER_SCORE_PERC_COL = 'res_ALGORITHMIC_TRACE_GENDER_SCORE_PERC'
RES_ALGORITHMIC_TRACE_POSTCODE_SCORE_PERC_COL = 'res_ALGORITHMIC_TRACE_POSTCODE_SCORE_PERC'

# deterministic diagnostic columns
PERSON_ID_COL = 'PERSON_ID'
PERSON_ID_TYPE_COL = 'PERSON_ID_TYPE'
MPS_LAST_STEP_ATTEMPTED_COL = 'MPS_LAST_STEP_ATTEMPTED'
MPS_SUCCESSFUL_STEP_COL = 'MPS_SUCCESSFUL_STEP'
PDS_MATCH_FLAG_COL = 'PDS_MATCH_FLAG'
SUPERSEDED_NHS_NUMBER_FLAG_COL = 'SUPERSEDED_NHS_NUMBER_FLAG'
NHS_NUMBER_HISTORY_LIST_COL = 'NHS_NUMBER_HISTORY_LIST'
SENSITIVE_FLAG_COL = 'SENSITIVE_FLAG'
MULTIPLE_PDS_MATCHES_FLAG_COL = 'MULTIPLE_PDS_MATCHES_FLAG'
MULTIPLE_MPS_ID_MATCHES_FLAG_COL = 'MULTIPLE_MPS_ID_MATCHES_FLAG'
MPS_MATCH_SCORE_COL = 'MPS_MATCH_SCORE'
MPS_ALGORITHMIC_MATCH_SCORE_COL = 'MPS_ALGORITHMIC_MATCH_SCORE'
FAMILYNAME_COL = 'FAMILYNAME'
GIVENNAME_COL = 'GIVENNAME'
DATEOFBIRTH_COL = 'DATEOFBIRTH'
GENDER_COL = 'GENDER'
POSTCODE_COL = 'POSTCODE'
MPS_DIAGNOSTICS_TIMESTAMP_COL = 'MPS_DIAGNOSTICS_TIMESTAMP'

# Adding Future Parameters
SANITY_CHECK_VERSION = 'TBA_SANITY_CHECK_VERSION'
DEBUG_LEVEL = 'TBA_DEBUG_LEVEL'